### ISSUE TITLE
Eslinter for 2 space instead of 4 spaces

### ISSUE THREAD

**Issue by Jeffchiucp** [arrangement-io/arrange-that-client#26]
@deonjo  are we still following the airbnb style guide through eslinter?

https://github.com/arrangement-io/arrange-that-client/blob/8000d382a3f6e1bbad9947e85563a55cf73340c7/.eslintrc#L9

**Comment by deonjo** [comment]
@atkwok fixed the eslinter

**Comment by Jeffchiucp** [comment]
nice!
